# Generated by Django 2.0.3 on 2018-05-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20180527_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('sur_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
        migrations.RenameField(
            model_name='class',
            old_name='class_liter',
            new_name='liter',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='class_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_id',
        ),
        migrations.AddField(
            model_name='class',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
