# Generated by Django 2.0.3 on 2018-05-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20180527_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('special', models.IntegerField()),
                ('name', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'Audience',
            },
        ),
        migrations.CreateModel(
            name='Scheduele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField()),
                ('class_liter', models.CharField(max_length=1)),
                ('weekday', models.IntegerField()),
                ('lesson_number', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('audience_id', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Scheduele',
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField()),
                ('class_number', models.IntegerField()),
                ('hours', models.IntegerField()),
            ],
            options={
                'db_table': 'StudyPlan',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('difficulty', models.IntegerField()),
            ],
            options={
                'db_table': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField()),
                ('class_number', models.IntegerField()),
                ('class_liter', models.CharField(max_length=1)),
                ('subject_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Workload',
            },
        ),
    ]
