# Generated by Django 2.0.3 on 2018-05-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_audience_scheduele_studyplan_subject_workload'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='need_spec_audience',
            field=models.BooleanField(default=False),
        ),
    ]
