# Generated by Django 2.0.3 on 2018-05-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_subject_need_spec_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='teacher_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scheduele',
            name='audience_id',
            field=models.IntegerField(null=True),
        ),
    ]
