# Generated by Django 2.0.3 on 2018-05-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20180527_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='special',
            field=models.IntegerField(default=0),
        ),
    ]
